# config/packages/security.yaml
security:
    password_hashers:
        App\Entity\Usuario:
            algorithm: bcrypt

    providers:
        users:
            entity:
                class: App\Entity\Usuario
                property: matricula

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        qr:
            pattern: ^/qrcode
            security: false

        main:
            lazy: true
            provider: users
            user_checker: app.user_checker
            form_login:
                login_path: app_login
                check_path: app_login
                always_use_default_target_path: true
            logout:
                path: app_logout

    role_hierarchy:
        ROLE_SUPER: [ROLE_ADM_FOFOE, ROLE_POSGRADO]

    access_control:
        - { path: '^/api/rest',                                      roles: PUBLIC_ACCESS }
        - { path: '/test-email/68b329da9893e34099c7d8ad5cb9c940',   roles: PUBLIC_ACCESS }
        - { path: '^/test/mails/enfermeria/',                        roles: PUBLIC_ACCESS }
        - { path: '/test',                                           roles: PUBLIC_ACCESS }
        - { path: '/aviso-privacidad',                               roles: PUBLIC_ACCESS }
        - { path: '^/enfermeria-alumno/login',                       roles: PUBLIC_ACCESS }
        - { path: '^/edu-per/request/login',                         roles: PUBLIC_ACCESS }
        - { path: '^/enfermeria-alumno/cedula-fiscal',               roles: [ROLE_ENFERMERIA_ALUMNO, ROLE_FOFOE_INICIO, ROLE_FOFOE_VALIDAR_PAGO, ROLE_FOFOE_VALIDAR_PAGO_MULTIPLE, ROLE_FOFOE_REGISTRAR_FACTURA] }
        - { path: '^/enfermeria-alumno',                             roles: [ROLE_ENFERMERIA_ALUMNO] }
        - { path: '^/directorio',                                    roles: PUBLIC_ACCESS }
        - { path: '^/consulta',                                      roles: PUBLIC_ACCESS }
        - { path: '^/admin/convenioscame',                           roles: [ROLE_SUPER, ROLE_ADM_FOFOE, ROLE_CAME, ROLE_JDES, ROLE_CAME_MINUS, ROLE_JDES_MINUS] }
        - { path: '^/admin/conveniosadmin/getconveniogral',          roles: [ROLE_SUPER, ROLE_CONVENIOS, ROLE_CAME, ROLE_JDES, ROLE_CONVENIOS_OBSERVER, ROLE_CAME_MINUS, ROLE_JDES_MINUS] }
        - { path: '^/admin/institucion',                             roles: [ROLE_SUPER, ROLE_CONVENIOS, ROLE_CONVENIOS_OBSERVER] }
        - { path: '^/admin/disciplina',                              roles: [ROLE_SUPER, ROLE_CONVENIOS, ROLE_CONVENIOS_OBSERVER] }
        - { path: '^/admin/coordfirmante',                           roles: [ROLE_SUPER, ROLE_CONVENIOS, ROLE_CONVENIOS_OBSERVER] }
        - { path: '^/admin/conveniosadmin',                          roles: [ROLE_SUPER, ROLE_CONVENIOS, ROLE_CONVENIOS_OBSERVER] }
        - { path: '^/admin/convenios-especiales',                    roles: [ROLE_SUPER, ROLE_CONVENIOS, ROLE_CONVENIOS_OBSERVER] }
        - { path: '^/admin/recurso',                                 roles: [ROLE_SUPER, ROLE_CONVENIOS, ROLE_CAME, ROLE_JDES, ROLE_CONVENIOS_OBSERVER, ROLE_CAME_MINUS, ROLE_JDES_MINUS] }
        - { path: '^/admin',                                         roles: [ROLE_SUPER, ROLE_ADM_FOFOE, ROLE_CAME, ROLE_JDES, ROLE_CAME_MINUS, ROLE_JDES_MINUS, ROLE_FOFOE_INICIO] }
        - { path: '^/profile',                                       roles: IS_AUTHENTICATED_FULLY }
        - { path: '^/ie/api',                                        roles: IS_AUTHENTICATED_FULLY }
        - { path: '^/ie',                                            roles: [ROLE_SUPER, ROLE_IE] }
        - { path: '^/came',                                          roles: [ROLE_SUPER, ROLE_CAME, ROLE_JDES, ROLE_CAME_MINUS, ROLE_JDES_MINUS] }
        - { path: '^/posgrado',                                      roles: [ROLE_SUPER, ROLE_POSGRADO, ROLE_CAME, ROLE_JDES, ROLE_CAME_MINUS, ROLE_JDES_MINUS] }
        - { path: '^/alumno/posgrado',                               roles: [ROLE_SUPER, ROLE_ALUMNO_POSGRADO] }
        - { path: '^/fofoe/inicio',                                  roles: [ROLE_SUPER, ROLE_FOFOE_INICIO] }
        - { path: '^/fofoe/validar-pago$',                           roles: [ROLE_SUPER, ROLE_FOFOE_VALIDAR_PAGO] }
        - { path: '^/fofoe/validar-pago-multiple',                   roles: [ROLE_SUPER, ROLE_FOFOE_VALIDAR_PAGO_MULTIPLE] }
        - { path: '^/fofoe/pagos',                                   roles: [ROLE_SUPER, ROLE_FOFOE_INICIO, ROLE_FOFOE_REGISTRAR_FACTURA] }
        - { path: '^/fofoe/detalle-ie',                              roles: [ROLE_SUPER, ROLE_FOFOE_INICIO, ROLE_FOFOE_DETALLE_INSTITUCION_EDUCATIVA] }
        - { path: '^/fofoe/reporte_ingresos',                        roles: [ROLE_SUPER, ROLE_FOFOE_REPORTE_INGS] }
        - { path: '^/fofoe/reporte_oportunidad_pago',                roles: [ROLE_SUPER, ROLE_FOFOE_REPORTE_OP] }
        - { path: '^/fofoe',                                         roles: [ROLE_SUPER, ROLE_FOFOE_INICIO, ROLE_FOFOE_VALIDAR_PAGO, ROLE_FOFOE_VALIDAR_PAGO_MULTIPLE, ROLE_FOFOE_REGISTRAR_FACTURA, ROLE_FOFOE_DETALLE_INSTITUCION_EDUCATIVA] }
        - { path: '^/pregrado/reporte',                              roles: [ROLE_SUPER, ROLE_REPORTE_CCS_DET] }
        - { path: '^/enfermeria/reporte_ciclos',                     roles: [ROLE_SUPER, ROLE_REPORTE_CCS_ENF] }
        - { path: '^/simulacion',                                    roles: [ROLE_SUPER, ROLE_SIMULACION] }
        - { path: '^/login',                                         roles: PUBLIC_ACCESS }
        - { path: '^/generarCaptcha',                                roles: PUBLIC_ACCESS }
        - { path: '^/captcha',                                       roles: PUBLIC_ACCESS }
        - { path: '^/formatos',                                      roles: IS_AUTHENTICATED_FULLY }
        - { path: '^/factura',                                       roles: IS_AUTHENTICATED_FULLY }
        - { path: '^/pago',                                          roles: IS_AUTHENTICATED_FULLY }
        - { path: '^/enfermeria',                                    roles: [ROLE_ENFERMERIA, ROLE_CAME, ROLE_CAME_MINUS] }
        - { path: '^/api/delegaciones',                              roles: IS_AUTHENTICATED_FULLY }
        - { path: '^/edu-per/participant',                           roles: [ROLE_SUPER, ROLE_EDU_PER_PARTICIPANTE] }
        - { path: '^/api/edu-per',                                   roles: IS_AUTHENTICATED_FULLY }
        - { path: '^/edu-per',                                       roles: [ROLE_SUPER, ROLE_EDU_PER] }
        - { path: '^/',                                              roles: IS_AUTHENTICATED_FULLY }
